-- Terpedia “how many” census queries.
-- Run from Google Colab with an authenticated BigQuery client.
-- Project: terpedia-489015. These queries are read-only.

-- 1. Discover tables and schemas.
SELECT table_schema, table_name, table_type
FROM `terpedia-489015`.region-us.INFORMATION_SCHEMA.TABLES
ORDER BY table_schema, table_name;

-- 2. Inspect columns before writing identity joins.
SELECT table_schema, table_name, column_name, data_type
FROM `terpedia-489015`.region-us.INFORMATION_SCHEMA.COLUMNS
WHERE table_schema = 'terpedia_raw'
  AND (
    REGEXP_CONTAINS(LOWER(column_name), r'(inchi|smiles|structure|compound|molecule|terpen)')
    OR column_name IN ('source_id', 'source_release', 'record_id')
  )
ORDER BY table_name, ordinal_position;

-- 3. Raw row counts. Confirm exact table names from step 1.
SELECT 'coconut_complete' AS source, COUNT(*) AS raw_rows
FROM `terpedia-489015.terpedia_raw.coconut_complete`
UNION ALL SELECT 'coconut_terpenoids', COUNT(*)
FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
UNION ALL SELECT 'coconut_terpenoids_pubchem', COUNT(*)
FROM `terpedia-489015.terpedia_raw.coconut_terpenoids_pubchem`
UNION ALL SELECT 'terokit_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_molecules`
UNION ALL SELECT 'terokit_purchasable_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_purchasable_molecules`
UNION ALL SELECT 'terokit_reaction_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
UNION ALL SELECT 'terokit_reaction_enzymes', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_reaction_enzymes`;

-- 4. Template for deduplicated source counts.
-- Replace `identity_key` with the actual column selected after step 2.
-- Prefer standard_inchi_key, then canonical structure hash; exclude nulls.
-- SELECT COUNT(*) AS unique_identities,
--        COUNTIF(standard_inchi_key IS NULL) AS missing_primary_key
-- FROM (
--   SELECT DISTINCT NULLIF(TRIM(standard_inchi_key), '') AS standard_inchi_key
--   FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
-- ) WHERE standard_inchi_key IS NOT NULL;

-- 4b. Classification audit template.
-- Adapt field names per source after step 2. Do not infer terpene status from
-- the table name alone. Preserve all evidence and provenance columns.
-- SELECT
--   source_id,
--   source_release,
--   manifest_uri,
--   retrieved_at,
--   content_sha256,
--   standard_inchi_key AS identity_key,
--   STRUCT(
--     chemical_class AS source_class,
--     direct_parent,
--     chebi_id,
--     pubchem_cid,
--     canonical_structure_hash
--   ) AS classification_evidence,
--   CASE
--     WHEN LOWER(chemical_class) IN ('terpene', 'terpenoid', 'isoprenoid')
--       OR LOWER(direct_parent) LIKE '%terpen%'
--       OR chebi_id IS NOT NULL OR pubchem_cid IS NOT NULL
--       THEN 'confirmed'
--     WHEN standard_inchi_key IS NOT NULL
--       AND canonical_structure_hash IS NOT NULL
--       THEN 'probable'
--     WHEN standard_inchi_key IS NULL
--       AND canonical_structure_hash IS NULL
--       THEN 'ambiguous'
--     ELSE 'excluded'
--   END AS classification_status
-- FROM `terpedia-489015.terpedia_raw.<source_table>`;

-- 4c. Count only classified molecule identities. Relation/measurement tables
-- must not be included in this union.
-- SELECT source_id, classification_status,
--        COUNT(*) AS source_rows,
--        COUNT(DISTINCT identity_key) AS unique_identities
-- FROM `<classification_audit_table>`
-- WHERE classification_status IN ('confirmed', 'probable')
-- GROUP BY source_id, classification_status;

-- 5. Pairwise overlap template after normalizing each source to identity_key.
-- WITH a AS (... SELECT DISTINCT identity_key FROM ...),
--      b AS (... SELECT DISTINCT identity_key FROM ...)
-- SELECT COUNT(*) AS overlap FROM a JOIN b USING (identity_key);

-- 5b. Concrete confirmed union: COCONUT terpenoids + TeroKit classified.
-- Both sources currently expose standard InChI reliably enough for this
-- first join. For the final report, prefer a canonical structure hash or
-- InChIKey generated by the same standardization pipeline for both sources.
WITH coconut AS (
  SELECT DISTINCT NULLIF(TRIM(standard_inchi), '') AS identity_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
  WHERE NULLIF(TRIM(standard_inchi), '') IS NOT NULL
), terokit AS (
  SELECT DISTINCT identity_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
), unioned AS (
  SELECT identity_key, 'coconut_terpenoids' AS source FROM coconut
  UNION ALL
  SELECT identity_key, 'terokit_classified' AS source FROM terokit
)
SELECT
  (SELECT COUNT(*) FROM coconut) AS coconut_unique,
  (SELECT COUNT(*) FROM terokit) AS terokit_unique,
  COUNT(DISTINCT identity_key) AS cross_source_union,
  COUNT(DISTINCT IF(source = 'coconut_terpenoids', identity_key, NULL))
    AS union_identities_seen_in_coconut,
  COUNT(DISTINCT IF(source = 'terokit_classified', identity_key, NULL))
    AS union_identities_seen_in_terokit
FROM unioned;

-- 5c. The overlap term used by the inclusion-exclusion check.
WITH coconut AS (
  SELECT DISTINCT NULLIF(TRIM(standard_inchi), '') AS identity_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
  WHERE NULLIF(TRIM(standard_inchi), '') IS NOT NULL
), terokit AS (
  SELECT DISTINCT identity_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
)
SELECT COUNT(*) AS cross_source_overlap
FROM coconut JOIN terokit USING (identity_key);

-- 5d. Typed chemical-identity sets. Prefixing the key type prevents an
-- InChI string from colliding with an InChIKey or non-canonical SMILES.
-- Prefer InChI, then InChIKey, then a labeled structure fallback.
WITH coconut AS (
  SELECT DISTINCT CASE
    WHEN NULLIF(TRIM(standard_inchi), '') IS NOT NULL
      THEN CONCAT('inchi:', TRIM(standard_inchi))
    WHEN NULLIF(TRIM(standard_inchi_key), '') IS NOT NULL
      THEN CONCAT('inchikey:', TRIM(standard_inchi_key))
    WHEN NULLIF(TRIM(canonical_smiles), '') IS NOT NULL
      THEN CONCAT('smiles:', TRIM(canonical_smiles))
  END AS identity_set_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
), terokit AS (
  SELECT DISTINCT CASE
    WHEN NULLIF(TRIM(inchi), '') IS NOT NULL
      THEN CONCAT('inchi:', TRIM(inchi))
    WHEN NULLIF(TRIM(smiles), '') IS NOT NULL
      THEN CONCAT('smiles:', TRIM(smiles))
  END AS identity_set_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
), unioned AS (
  SELECT identity_set_key, 'coconut' AS source FROM coconut
  WHERE identity_set_key IS NOT NULL
  UNION ALL
  SELECT identity_set_key, 'terokit' AS source FROM terokit
  WHERE identity_set_key IS NOT NULL
)
SELECT
  COUNT(DISTINCT identity_set_key) AS union_set_size,
  COUNT(DISTINCT IF(source = 'coconut', identity_set_key, NULL))
    AS coconut_set_size,
  COUNT(DISTINCT IF(source = 'terokit', identity_set_key, NULL))
    AS terokit_set_size,
  COUNT(DISTINCT IF(identity_set_key LIKE 'inchi:%', identity_set_key, NULL))
    AS inchi_set_members,
  COUNT(DISTINCT IF(identity_set_key LIKE 'inchikey:%', identity_set_key, NULL))
    AS inchikey_fallback_members,
  COUNT(DISTINCT IF(identity_set_key LIKE 'smiles:%', identity_set_key, NULL))
    AS smiles_fallback_members
FROM unioned;

-- 6. RDF/SPARQL query templates for https://kb.terpedia.com/sparql.
-- Run these through requests.get(..., params={'query': query, 'format': 'json'}).
-- Count terpenoids and descendants:
-- PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
-- SELECT (COUNT(DISTINCT ?entity) AS ?n) WHERE {
--   ?entity a/rdfs:subClassOf* <http://purl.obolibrary.org/obo/CHEBI_35186> .
-- }
-- Count labels containing terpene/terpenoid (discovery diagnostic only):
-- SELECT (COUNT(DISTINCT ?entity) AS ?n) WHERE {
--   ?entity ?predicate ?label .
--   FILTER(isLiteral(?label) && CONTAINS(LCASE(STR(?label)), 'terpen'))
-- }

-- 7. TeroKit completeness proxy: confirmed terpene/terpenoid products that
-- occur on the product side of at least one reaction.
-- Do not count every reaction row: rows may repeat across releases, and
-- reaction participation is not the same as production.
WITH confirmed_molecules AS (
  SELECT DISTINCT source_record_id
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
), product_edges AS (
  SELECT DISTINCT reaction_id, product_id
  FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
  WHERE NULLIF(TRIM(product_id), '') IS NOT NULL
)
SELECT
  COUNT(DISTINCT p.reaction_id) AS reactions_with_products,
  COUNT(DISTINCT p.product_id) AS distinct_reaction_products,
  COUNT(DISTINCT IF(c.source_record_id IS NOT NULL, p.product_id, NULL))
    AS distinct_confirmed_terpenoid_products,
  COUNT(DISTINCT IF(c.source_record_id IS NULL, p.product_id, NULL))
    AS products_not_confirmed_as_terpenoids
FROM product_edges AS p
LEFT JOIN confirmed_molecules AS c
  ON c.source_record_id = p.product_id;

-- 7b. Structure-identity version: collapse multiple TeroKit source IDs or
-- releases onto identity_key after selecting product-side reaction edges.
WITH product_edges AS (
  SELECT DISTINCT reaction_id, product_id
  FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
  WHERE NULLIF(TRIM(product_id), '') IS NOT NULL
), classified_products AS (
  SELECT DISTINCT source_record_id, identity_key, classification_status
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE identity_key IS NOT NULL
)
SELECT
  COUNT(DISTINCT IF(c.classification_status =
      'confirmed_source_declared_terpenoid', c.identity_key, NULL))
    AS distinct_confirmed_terpenoid_product_identities,
  COUNT(DISTINCT IF(c.classification_status = 'ambiguous_not_confirmed',
      c.identity_key, NULL)) AS distinct_ambiguous_product_identities
FROM product_edges AS p
JOIN classified_products AS c
  ON c.source_record_id = p.product_id;
