-- Terpedia “how many” census queries.
-- Run from Google Colab with an authenticated BigQuery client.
-- Project: terpedia-489015. These queries are read-only.

-- 1. Discover tables and schemas.
SELECT table_schema, table_name, table_type
FROM `terpedia-489015`.region-us.INFORMATION_SCHEMA.TABLES
ORDER BY table_schema, table_name;

-- 2. Inspect columns before writing identity joins.
SELECT table_schema, table_name, column_name, data_type
FROM `terpedia-489015`.region-us.INFORMATION_SCHEMA.COLUMNS
WHERE table_schema = 'terpedia_raw'
  AND (
    REGEXP_CONTAINS(LOWER(column_name), r'(inchi|smiles|structure|compound|molecule|terpen)')
    OR column_name IN ('source_id', 'source_release', 'record_id')
  )
ORDER BY table_name, ordinal_position;

-- 3. Raw row counts. Confirm exact table names from step 1.
SELECT 'coconut_complete' AS source, COUNT(*) AS raw_rows
FROM `terpedia-489015.terpedia_raw.coconut_complete`
UNION ALL SELECT 'coconut_terpenoids', COUNT(*)
FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
UNION ALL SELECT 'coconut_terpenoids_pubchem', COUNT(*)
FROM `terpedia-489015.terpedia_raw.coconut_terpenoids_pubchem`
UNION ALL SELECT 'terokit_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_molecules`
UNION ALL SELECT 'terokit_purchasable_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_purchasable_molecules`
UNION ALL SELECT 'terokit_reaction_molecules', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
UNION ALL SELECT 'terokit_reaction_enzymes', COUNT(*)
FROM `terpedia-489015.terpedia_raw.terokit_reaction_enzymes`;

-- 4. Template for deduplicated source counts.
-- Replace `identity_key` with the actual column selected after step 2.
-- Prefer standard_inchi_key, then canonical structure hash; exclude nulls.
-- SELECT COUNT(*) AS unique_identities,
--        COUNTIF(standard_inchi_key IS NULL) AS missing_primary_key
-- FROM (
--   SELECT DISTINCT NULLIF(TRIM(standard_inchi_key), '') AS standard_inchi_key
--   FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
-- ) WHERE standard_inchi_key IS NOT NULL;

-- 4b. Classification audit template.
-- Adapt field names per source after step 2. Do not infer terpene status from
-- the table name alone. Preserve all evidence and provenance columns.
-- SELECT
--   source_id,
--   source_release,
--   manifest_uri,
--   retrieved_at,
--   content_sha256,
--   standard_inchi_key AS identity_key,
--   STRUCT(
--     chemical_class AS source_class,
--     direct_parent,
--     chebi_id,
--     pubchem_cid,
--     canonical_structure_hash
--   ) AS classification_evidence,
--   CASE
--     WHEN LOWER(chemical_class) IN ('terpene', 'terpenoid', 'isoprenoid')
--       OR LOWER(direct_parent) LIKE '%terpen%'
--       THEN 'confirmed'
--     WHEN chebi_id IS NOT NULL OR pubchem_cid IS NOT NULL
--       THEN 'identity_resolved_class_unconfirmed'
--     WHEN standard_inchi_key IS NOT NULL
--       AND canonical_structure_hash IS NOT NULL
--       THEN 'probable'
--     WHEN standard_inchi_key IS NULL
--       AND canonical_structure_hash IS NULL
--       THEN 'ambiguous'
--     ELSE 'excluded'
--   END AS classification_status
-- FROM `terpedia-489015.terpedia_raw.<source_table>`;

-- 4c. Count only classified molecule identities. Relation/measurement tables
-- must not be included in this union.
-- SELECT source_id, classification_status,
--        COUNT(*) AS source_rows,
--        COUNT(DISTINCT identity_key) AS unique_identities
-- FROM `<classification_audit_table>`
-- WHERE classification_status IN ('confirmed', 'probable')
-- GROUP BY source_id, classification_status;

-- 5. Pairwise overlap template after normalizing each source to identity_key.
-- WITH a AS (... SELECT DISTINCT identity_key FROM ...),
--      b AS (... SELECT DISTINCT identity_key FROM ...)
-- SELECT COUNT(*) AS overlap FROM a JOIN b USING (identity_key);

-- 5b. Concrete confirmed union: COCONUT terpenoids + TeroKit classified.
-- Both sources currently expose standard InChI reliably enough for this
-- first join. For the final report, prefer a canonical structure hash or
-- InChIKey generated by the same standardization pipeline for both sources.
WITH coconut AS (
  SELECT DISTINCT NULLIF(TRIM(standard_inchi), '') AS identity_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
  WHERE NULLIF(TRIM(standard_inchi), '') IS NOT NULL
), terokit AS (
  SELECT DISTINCT identity_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
), unioned AS (
  SELECT identity_key, 'coconut_terpenoids' AS source FROM coconut
  UNION ALL
  SELECT identity_key, 'terokit_classified' AS source FROM terokit
)
SELECT
  (SELECT COUNT(*) FROM coconut) AS coconut_unique,
  (SELECT COUNT(*) FROM terokit) AS terokit_unique,
  COUNT(DISTINCT identity_key) AS cross_source_union,
  COUNT(DISTINCT IF(source = 'coconut_terpenoids', identity_key, NULL))
    AS union_identities_seen_in_coconut,
  COUNT(DISTINCT IF(source = 'terokit_classified', identity_key, NULL))
    AS union_identities_seen_in_terokit
FROM unioned;

-- 5c. The overlap term used by the inclusion-exclusion check.
WITH coconut AS (
  SELECT DISTINCT NULLIF(TRIM(standard_inchi), '') AS identity_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
  WHERE NULLIF(TRIM(standard_inchi), '') IS NOT NULL
), terokit AS (
  SELECT DISTINCT identity_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
)
SELECT COUNT(*) AS cross_source_overlap
FROM coconut JOIN terokit USING (identity_key);

-- 5d. Typed chemical-identity sets. Prefixing the key type prevents an
-- InChI string from colliding with an InChIKey or non-canonical SMILES.
-- Prefer InChI, then InChIKey, then a labeled structure fallback.
WITH coconut AS (
  SELECT DISTINCT CASE
    WHEN NULLIF(TRIM(standard_inchi), '') IS NOT NULL
      THEN CONCAT('inchi:', TRIM(standard_inchi))
    WHEN NULLIF(TRIM(standard_inchi_key), '') IS NOT NULL
      THEN CONCAT('inchikey:', TRIM(standard_inchi_key))
    WHEN NULLIF(TRIM(canonical_smiles), '') IS NOT NULL
      THEN CONCAT('smiles:', TRIM(canonical_smiles))
  END AS identity_set_key
  FROM `terpedia-489015.terpedia_raw.coconut_terpenoids`
), terokit AS (
  SELECT DISTINCT CASE
    WHEN NULLIF(TRIM(inchi), '') IS NOT NULL
      THEN CONCAT('inchi:', TRIM(inchi))
    WHEN NULLIF(TRIM(smiles), '') IS NOT NULL
      THEN CONCAT('smiles:', TRIM(smiles))
  END AS identity_set_key
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
), unioned AS (
  SELECT identity_set_key, 'coconut' AS source FROM coconut
  WHERE identity_set_key IS NOT NULL
  UNION ALL
  SELECT identity_set_key, 'terokit' AS source FROM terokit
  WHERE identity_set_key IS NOT NULL
)
SELECT
  COUNT(DISTINCT identity_set_key) AS union_set_size,
  COUNT(DISTINCT IF(source = 'coconut', identity_set_key, NULL))
    AS coconut_set_size,
  COUNT(DISTINCT IF(source = 'terokit', identity_set_key, NULL))
    AS terokit_set_size,
  COUNT(DISTINCT IF(identity_set_key LIKE 'inchi:%', identity_set_key, NULL))
    AS inchi_set_members,
  COUNT(DISTINCT IF(identity_set_key LIKE 'inchikey:%', identity_set_key, NULL))
    AS inchikey_fallback_members,
  COUNT(DISTINCT IF(identity_set_key LIKE 'smiles:%', identity_set_key, NULL))
    AS smiles_fallback_members
FROM unioned;

-- 6. RDF/SPARQL query templates for https://kb.terpedia.com/sparql.
-- Run these through requests.get(..., params={'query': query, 'format': 'json'}).
-- Count terpenoids and descendants:
-- PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
-- SELECT (COUNT(DISTINCT ?entity) AS ?n) WHERE {
--   ?entity a/rdfs:subClassOf* <http://purl.obolibrary.org/obo/CHEBI_35186> .
-- }
-- Count labels containing terpene/terpenoid (discovery diagnostic only):
-- SELECT (COUNT(DISTINCT ?entity) AS ?n) WHERE {
--   ?entity ?predicate ?label .
--   FILTER(isLiteral(?label) && CONTAINS(LCASE(STR(?label)), 'terpen'))
-- }

-- 7. TeroKit completeness proxy: confirmed terpene/terpenoid products that
-- occur on the product side of at least one reaction.
-- Do not count every reaction row: rows may repeat across releases, and
-- reaction participation is not the same as production.
WITH confirmed_molecules AS (
  SELECT DISTINCT source_record_id
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE classification_status = 'confirmed_source_declared_terpenoid'
    AND identity_key IS NOT NULL
), product_edges AS (
  SELECT DISTINCT reaction_id, product_id
  FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
  WHERE NULLIF(TRIM(product_id), '') IS NOT NULL
)
SELECT
  COUNT(DISTINCT p.reaction_id) AS reactions_with_products,
  COUNT(DISTINCT p.product_id) AS distinct_reaction_products,
  COUNT(DISTINCT IF(c.source_record_id IS NOT NULL, p.product_id, NULL))
    AS distinct_confirmed_terpenoid_products,
  COUNT(DISTINCT IF(c.source_record_id IS NULL, p.product_id, NULL))
    AS products_not_confirmed_as_terpenoids
FROM product_edges AS p
LEFT JOIN confirmed_molecules AS c
  ON c.source_record_id = p.product_id;

-- 7b. Structure-identity version: collapse multiple TeroKit source IDs or
-- releases onto identity_key after selecting product-side reaction edges.
WITH product_edges AS (
  SELECT DISTINCT reaction_id, product_id
  FROM `terpedia-489015.terpedia_raw.terokit_reaction_molecules`
  WHERE NULLIF(TRIM(product_id), '') IS NOT NULL
), classified_products AS (
  SELECT DISTINCT source_record_id, identity_key, classification_status
  FROM `terpedia-489015.terpedia_raw.terokit_molecule_classification`
  WHERE identity_key IS NOT NULL
)
SELECT
  COUNT(DISTINCT IF(c.classification_status =
      'confirmed_source_declared_terpenoid', c.identity_key, NULL))
    AS distinct_confirmed_terpenoid_product_identities,
  COUNT(DISTINCT IF(c.classification_status = 'ambiguous_not_confirmed',
      c.identity_key, NULL)) AS distinct_ambiguous_product_identities
FROM product_edges AS p
JOIN classified_products AS c
  ON c.source_record_id = p.product_id;

-- 8. T# cross-reference coverage. This reports only exact-key matches; it is
-- not a claim that sources lacking compatible chemical keys are absent.
SELECT
  x.source_name,
  COUNT(*) AS crossref_records,
  COUNT(DISTINCT t.terpene_id) AS t_ids
FROM `terpedia-489015.terpedia_core.terpene_identity_set` AS t,
  UNNEST(t.source_crossrefs) AS x
GROUP BY x.source_name
ORDER BY x.source_name;

-- 8b. Overall T# coverage sanity check.
SELECT
  COUNT(*) AS t_rows,
  COUNT(DISTINCT terpene_id) AS t_ids,
  COUNTIF(ARRAY_LENGTH(source_crossrefs) > 0) AS rows_with_crossrefs
FROM `terpedia-489015.terpedia_core.terpene_identity_set`;

-- 8c. Carbon-count grouping used by the T# prefix.
SELECT
  terpene_size_class,
  carbon_count,
  COUNT(*) AS t_ids,
  MIN(terpene_id) AS first_t_id,
  MAX(terpene_id) AS last_t_id
FROM `terpedia-489015.terpedia_core.terpene_identity_set`
GROUP BY terpene_size_class, carbon_count
ORDER BY carbon_count;

-- 9. Structure-based ordering. Join this versioned table to obtain the
-- scaffold-family display order without changing the chemical identity key.
SELECT
  t.terpene_id,
  s.similarity_rank,
  s.scaffold_smiles,
  s.scaffold_hash,
  s.fingerprint_hash,
  s.similarity_method
FROM `terpedia-489015.terpedia_core.terpene_identity_set` AS t
JOIN `terpedia-489015.terpedia_core.terpene_similarity_order_20260904` AS s
USING (terpene_id, identity_set_key)
ORDER BY s.similarity_rank;

-- 10. Exact PubChem CID recovery for T# identities that lacked a PubChem ID
-- in the initial COCONUT-derived subset.
SELECT
  COUNT(*) AS queried_t_ids,
  COUNTIF(pubchem_match_status = 'matched') AS newly_matched_t_ids,
  COUNTIF(pubchem_match_status = 'not_found') AS unmatched_t_ids,
  COUNTIF(ARRAY_LENGTH(SPLIT(pubchem_cids, ';')) > 1) AS multi_cid_t_ids,
  MIN(retrieved_at) AS retrieved_at
FROM `terpedia-489015.terpedia_core.terpene_pubchem_lookup_20260904`;

-- 11. TeroKit source-declared purchasability mapped into T# identities.
WITH terokit_t_ids AS (
  SELECT DISTINCT t.terpene_id, x.source_record_id
  FROM `terpedia-489015.terpedia_core.terpene_identity_set` AS t,
    UNNEST(t.source_crossrefs) AS x
  WHERE x.source_name = 'terokit_classified'
), purchasable AS (
  SELECT DISTINCT source_record_id, vendor, vendor_code, website
  FROM `terpedia-489015.terpedia_raw.terokit_purchasable_molecules`
)
SELECT
  COUNT(DISTINCT p.source_record_id) AS purchasable_source_records,
  COUNT(DISTINCT t.terpene_id) AS purchasable_t_ids,
  COUNT(DISTINCT p.vendor) AS vendor_labels,
  COUNT(DISTINCT IF(t.terpene_id IS NULL, p.source_record_id, NULL))
    AS purchasable_records_without_t_id
FROM purchasable AS p
LEFT JOIN terokit_t_ids AS t USING (source_record_id);

-- 12. MARTS-DB enzyme, reaction, product, and catalog-promiscuity census.
-- Multi-product association is an observed database property, not proof that
-- every product is formed by one enzyme under the same conditions.
WITH base AS (
  SELECT *
  FROM `terpedia-489015.terpedia_core.terpene_enzyme_evidence_marts`
), per_enzyme AS (
  SELECT
    marts_enzyme_id,
    COUNT(DISTINCT product_smiles) AS distinct_products
  FROM base
  WHERE NULLIF(TRIM(marts_enzyme_id), '') IS NOT NULL
  GROUP BY marts_enzyme_id
)
SELECT
  (SELECT COUNT(*) FROM base) AS reaction_enzyme_records,
  (SELECT COUNT(DISTINCT marts_reaction_id) FROM base) AS distinct_reactions,
  (SELECT COUNT(DISTINCT marts_enzyme_id) FROM base) AS distinct_enzymes,
  (SELECT COUNT(DISTINCT NULLIF(TRIM(aminoacid_sequence), '')) FROM base)
    AS distinct_sequences,
  (SELECT COUNT(DISTINCT product_smiles) FROM base)
    AS distinct_product_structures,
  (SELECT COUNT(DISTINCT substrate_smiles) FROM base)
    AS distinct_substrate_structures,
  (SELECT COUNTIF(distinct_products > 1) FROM per_enzyme)
    AS enzymes_with_multiple_products,
  (SELECT AVG(distinct_products) FROM per_enzyme) AS mean_products_per_enzyme,
  (SELECT MAX(distinct_products) FROM per_enzyme) AS max_products_per_enzyme;

-- 13. Current T# metabolic-network coverage. Keep isomeric and
-- stereo-insensitive matches separate.
SELECT
  structure_match_mode,
  COUNT(*) AS edge_rows,
  COUNT(DISTINCT CONCAT(product_terpene_id, '|', precursor_terpene_id))
    AS distinct_product_precursor_pairs,
  COUNT(DISTINCT product_terpene_id) AS product_t_ids,
  COUNT(DISTINCT precursor_terpene_id) AS precursor_t_ids,
  COUNT(DISTINCT reaction_id) AS reaction_rules
FROM `terpedia-489015.terpedia_core.terpene_metabolic_map_edges_current_latest_v3`
GROUP BY structure_match_mode
ORDER BY structure_match_mode;

SELECT *
FROM `terpedia-489015.terpedia_core.terpene_metabolic_map_coverage_dashboard_current_latest_v3`
ORDER BY stratum;

-- 14. Classification and structure-quality flags. These are review flags,
-- not automatic exclusions; each flagged identity retains source evidence.
SELECT
  COUNT(*) AS t_rows,
  COUNT(DISTINCT inchi) AS distinct_standard_inchi,
  COUNT(DISTINCT inchikey) AS distinct_stored_full_inchikey,
  COUNT(DISTINCT smiles) AS distinct_stored_smiles,
  COUNTIF(inchikey IS NULL OR TRIM(inchikey) = '') AS missing_stored_inchikey,
  COUNTIF(STRPOS(smiles, '.') > 0) AS disconnected_smiles_rows,
  COUNTIF(REGEXP_CONTAINS(molecular_formula, r'F([^a-z]|$)'))
    AS fluorinated_formula_rows
FROM `terpedia-489015.terpedia_core.terpene_identity_set`;

SELECT
  source,
  COUNT(DISTINCT terpene_id) AS fluorinated_t_ids
FROM `terpedia-489015.terpedia_core.terpene_identity_set`,
  UNNEST(source_memberships) AS source
WHERE REGEXP_CONTAINS(molecular_formula, r'F([^a-z]|$)')
GROUP BY source
ORDER BY fluorinated_t_ids DESC;

-- 15. Uniform exact PubChem coverage and BioAssay participation.
WITH t_cids AS (
  SELECT terpene_id, cid
  FROM `terpedia-489015.terpedia_core.terpene_pubchem_lookup_all_20260904`,
    UNNEST(SPLIT(pubchem_cids, ';')) AS cid
  WHERE cid != ''
), aids AS (
  SELECT pubchem_cid, aid
  FROM `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_lookup_20260904`,
    UNNEST(SPLIT(pubchem_aids, ';')) AS aid
  WHERE aid != ''
)
SELECT
  (SELECT COUNT(*)
   FROM `terpedia-489015.terpedia_core.terpene_pubchem_lookup_all_20260904`)
    AS total_t_ids,
  (SELECT COUNTIF(pubchem_match_status = 'matched')
   FROM `terpedia-489015.terpedia_core.terpene_pubchem_lookup_all_20260904`)
    AS t_ids_with_pubchem_cid,
  (SELECT COUNTIF(bioassay_count > 0)
   FROM `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_lookup_20260904`)
    AS cids_with_bioassays,
  COUNT(DISTINCT t.terpene_id) AS t_ids_with_bioassays,
  COUNT(DISTINCT a.aid) AS distinct_bioassays,
  COUNT(*) AS cid_aid_t_links
FROM aids AS a
JOIN t_cids AS t ON t.cid = a.pubchem_cid;

-- 16. Mutually exclusive T# partition by PubChem active/inactive AID links.
WITH t_cids AS (
  SELECT terpene_id, cid
  FROM `terpedia-489015.terpedia_core.terpene_pubchem_lookup_all_20260904`,
    UNNEST(SPLIT(pubchem_cids, ';')) AS cid
  WHERE cid != ''
), all_t AS (
  SELECT DISTINCT terpene_id
  FROM t_cids JOIN `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_lookup_20260904` b
    ON cid = b.pubchem_cid
  WHERE b.bioassay_count > 0
), active_t AS (
  SELECT DISTINCT terpene_id
  FROM t_cids JOIN `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_active_lookup_20260904` b
    ON cid = b.pubchem_cid
  WHERE b.bioassay_count > 0
), inactive_t AS (
  SELECT DISTINCT terpene_id
  FROM t_cids JOIN `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_inactive_lookup_20260904` b
    ON cid = b.pubchem_cid
  WHERE b.bioassay_count > 0
)
SELECT
  CASE
    WHEN a.terpene_id IS NOT NULL AND i.terpene_id IS NOT NULL
      THEN 'active_and_inactive'
    WHEN a.terpene_id IS NOT NULL THEN 'active_only'
    WHEN i.terpene_id IS NOT NULL THEN 'inactive_only'
    WHEN x.terpene_id IS NOT NULL THEN 'assay_without_active_or_inactive_aid'
    ELSE 'no_assay'
  END AS category,
  COUNT(*) AS t_ids
FROM `terpedia-489015.terpedia_core.terpene_identity_set` AS t
LEFT JOIN all_t AS x USING (terpene_id)
LEFT JOIN active_t AS a USING (terpene_id)
LEFT JOIN inactive_t AS i USING (terpene_id)
GROUP BY category
ORDER BY t_ids DESC;

-- 16b. AID-level overlap of active and inactive associations. The same assay
-- may classify different mapped compounds, or different submitted records of
-- a compound, differently.
WITH active AS (
  SELECT DISTINCT aid
  FROM `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_active_lookup_20260904`,
    UNNEST(SPLIT(pubchem_aids, ';')) AS aid
  WHERE aid != ''
), inactive AS (
  SELECT DISTINCT aid
  FROM `terpedia-489015.terpedia_core.terpene_pubchem_bioassay_inactive_lookup_20260904`,
    UNNEST(SPLIT(pubchem_aids, ';')) AS aid
  WHERE aid != ''
)
SELECT
  (SELECT COUNT(*) FROM active) AS active_aids,
  (SELECT COUNT(*) FROM inactive) AS inactive_aids,
  (SELECT COUNT(*) FROM active JOIN inactive USING (aid))
    AS aids_with_both_outcome_classes,
  (SELECT COUNT(*) FROM (
    SELECT aid FROM active UNION DISTINCT SELECT aid FROM inactive
  )) AS aids_with_active_or_inactive;

-- 17. PubMed function-by-terpene panel audit. Pair hit counts cannot be summed
-- into unique articles because one PMID may satisfy multiple queries.
WITH pairs AS (
  SELECT
    function_label,
    terpene_label,
    MAX(pubmed_count) AS pubmed_count
  FROM `terpedia-489015.terpedia_raw.pubmed_function_terpene_cooccurrence`
  GROUP BY function_label, terpene_label
)
SELECT
  (SELECT COUNT(*)
   FROM `terpedia-489015.terpedia_raw.pubmed_function_terpene_cooccurrence`)
    AS raw_rows,
  COUNT(*) AS distinct_pairs,
  COUNT(DISTINCT function_label) AS distinct_function_labels,
  COUNT(DISTINCT terpene_label) AS distinct_terpene_labels,
  COUNTIF(pubmed_count > 0) AS positive_pairs,
  COUNTIF(pubmed_count = 0) AS zero_hit_pairs,
  SUM(pubmed_count) AS summed_pair_hits_not_unique_pmids
FROM pairs;
